version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    deploy:
      resources:
        limits:
          cpus: 1.00
          memory: 1024M
        reservations:
          cpus: 0.50
          memory: 512M
    ports:
      - 3000:3000
    networks:
      - app

networks:
  app:
